require: rubocop-factory_bot

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - bundle/**/*
    - app/controllers/concerns/hyrax/works_controller_behavior.rb # Hyrax override

Metrics/MethodLength:
  Exclude:
    - lib/preservation_events.rb

Rails/Exit:
  Exclude:
    - config/deploy.rb
    - lib/fedora/migrate_fedora3_objects.rb

Style/MultilineBlockChain:
  Exclude:
    - config/environments/development.rb

