require: rubocop-factory_bot

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - bundle/**/*
    - app/controllers/concerns/hyrax/works_controller_behavior.rb # Hyrax override

Metrics/AbcSize:
  Exclude:
    - app/controllers/concerns/hyrax/works_controller_behavior.rb
    - app/indexers/self_deposit/indexers/file_set_indexer.rb
    - app/services/hyrax/valkyrie_upload.rb
    - config/initializers/hyrax_edit_permissions_service_override.rb

Metrics/MethodLength:
  Exclude:
    - lib/preservation_events.rb

Rails/Exit:
  Exclude:
    - config/deploy.rb
    - lib/fedora/migrate_fedora3_objects.rb
    - lib/metadata/extract_mods_metadata_to_csv.rb

Rails/Output:
  Exclude:
    - lib/fedora/migrate_fedora3_objects.rb
    - lib/metadata/extract_mods_metadata_to_csv.rb

Style/MultilineBlockChain:
  Exclude:
    - config/environments/development.rb

