require: rubocop-factory_bot

inherit_gem:
    bixby: bixby_default.yml

AllCops:
    TargetRubyVersion: 3.2
    DisplayCopNames: true
    Exclude:
        - bin/**/*
        - db/**/*
        - tmp/**/*
        - vendor/**/*
        - node_modules/**/*
        - bundle/**/*