AWSTemplateFormatVersion: 2010-09-09
Resources:
  ShibServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0cf10cdf9fcd62d37"
      InstanceType: "t3.micro"
      KeyName: "library_team.pem"
      PropagateTagsToVolumeOnCreation: True
      SecurityGroupIds:
        - "sg-05d9c90cf588fbf55"
      SubnetId: "subnet-0289823249b0d4c77"
      Tags:
        - Key: "Name"
          Value: !Sub 'OE24-shib'
        - Key: "EmoryApplicationName"
          Value: "Openemory"
        - Key: "AnsibleDesignation"
          Value: "OE24shib"

