AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3NameParameter:
    Type: String
    Default: fedora-depo-arch-binaries
    Description: the name for the bucket
Resources:
  FedoraDepoS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 
        Ref: S3NameParameter
