AWSTemplateFormatVersion: 2010-09-09 
Parameters:
  EnvironmentParameter:
    Type: String
Resources:
  FedoraDepoRedis:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub 'OE24-redis-${EnvironmentParameter}'
      ReplicationGroupDescription: 'openemory self deposit'
      NumCacheClusters: 3
      Engine: Redis
      EngineVersion: 6.2
      AutomaticFailoverEnabled: true
      CacheNodeType: cache.t3.micro
      CacheSubnetGroupName: elasticache-redis-test
      SecurityGroupIds:
        - sg-00e0f950d60629f7e
