AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EnvironmentParameter:
    Type: String
    Default: arch
    Description: arch, test, or production
  MasterPassParameter:
    Type: String
Resources:  
  FedoraDepoRDS:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Sub 'fedora-depo-${EnvironmentParameter}' 
      AllocatedStorage: 40
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: 15.5
      AvailabilityZone: us-east-1a
      VPCSecurityGroups:
        - sg-0eac4ee948d55b836
      DBSubnetGroupName: blackcat-arch-mysql-db-20210222184025887100000001
      DBName: !Sub 'oe24${EnvironmentParameter}'
      DBParameterGroupName: selfdeposit
      MasterUsername: postgres
      MasterUserPassword: !Ref MasterPassParameter
      StorageEncrypted: true
      PubliclyAccessible: false
      BackupRetentionPeriod: 0
