AWSTemplateFormatVersion: 2010-09-09
Resources:  
  FedoraDepoRDS:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: postgres
