# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:collection_resource CollectionResource`

attributes:
  administrative_unit:
    type: string
    multiple: false
    form:
      primary: true
      multiple: false
    predicate: http://id.loc.gov/vocabulary/relators/cur
  contact_information:
    type: string
    multiple: false
    form:
      primary: true
      multiple: false
    predicate: http://www.rdaregistry.info/Elements/u/#P60490
  description:
    type: string
    multiple: true
    form:
      required: true
      primary: true
    index_keys:
      - "description_tesim"
    predicate: http://purl.org/dc/elements/1.1/description
  notes:
    type: string
    multiple: true
    form:
      primary: false
      multiple: true
    predicate: http://www.w3.org/2004/02/skos/core#note
  subject_geo:
    type: string
    multiple: false
    form:
      primary: false
      multiple: true
    predicate: http://purl.org/dc/elements/1.1/coverage
    index_keys:
      - 'subject_geo_ssim'
  subject_names:
    type: string
    multiple: false
    form:
      primary: false
      multiple: true
    predicate: http://purl.org/dc/elements/1.1/subject#names
    index_keys:
      - 'subject_names_ssim'
