attributes:
  emory_persistent_id:
    type: string
    multiple: false
    index_keys:
      - 'emory_persistent_id_ssi'
    predicate: http://metadata.emory.edu/vocab/cor-terms#emoryPersistentId
  file_set_use:
    type: string
    multiple: false
    form:
      required: false
      primary: false
    predicate: http://metadata.emory.edu/vocab/cor-terms#fileSetUse
    index_keys:
      - "file_set_use_ssi"
  preservation_event_ids:
    type: string
    predicate: http://metadata.emory.edu/vocab/cor-terms#preservationEventIDs
