terms:
  - id: Preprint (Prior to Peer Review)
    term: Preprint (Prior to Peer Review)
  - id: Author Accepted Manuscript (After Peer Review)
    term: Author Accepted Manuscript (After Peer Review)
  - id: Final Published Version
    term: Final Published Version
