development:
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>
  password: <%= ENV['REDIS_PASSWORD'] %>
test:
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>
  password: <%= ENV['REDIS_PASSWORD'] %>
production:
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379/0') %>
  password: <%= ENV['REDIS_PASSWORD'] %>
