---
:queues:
  - [ingest, 4]

:limits:
  ingest: 7

:timeout: 300

:max_retries: 3

test: # n/a
  :concurrency: 1

development:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 2 %>
  :logfile: ./log/sidekiq_development.log

production:
  :concurrency: <%= ENV['SIDEKIQ_WORKERS'] || 15 %>
