default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  toolbar1: undo redo | styles | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image
  plugins:
    - advlist
    - anchor
    - autolink
    - charmap
    - code
    - fullscreen
    - help
    - image
    - insertdatetime
    - link
    - lists
    - media
    - preview
    - searchreplace
    - table
    - visualblocks
custom:
  <<: *default
