---
- name: deploy main 
  hosts: localhost
  vars:
    - deployhost: "{{ ENV | upper }}_SERVER_IP"  
  tasks:
  - name: Create and provision resources for Fedora Self Deposit
    import_playbook: copy-prod-env.yaml
  - name: checkout latest
    git:
      repo: https://github.com/emory-libraries/dlp-selfdeposit
      dest: files/checkout
      version: main
  - name: get ec2host ip
    ec2_instance_info:
      filters:
        "tag:Name": OE24-hyrax-{{ ENV }}
    register: instance_ip
  - name: deploy
    shell:
      cmd: "BRANCH=main bundle exec cap {{ ENV }} deploy"
      chdir: files/checkout
    args:
      executable: /bin/bash
    environment: 
      "{{ deploy_host }}": "{{ instance_ip.instances[0].network_interfaces[0].private_ip_address }}"
    register: errors
    ignore_errors: yes
  - name: print deploy results
    debug:
      msg: "{{ errors }}"
