---
- name: deploy main 
  hosts: localhost
  vars:
    - DBPASSWORD: "{{ lookup('amazon.aws.aws_secret','oe24-{{ ENV }}-dbuser-password.password',nested=true) }}" 
    - deployhost: "{{ ENV | upper }}_SERVER_IP"  
  tasks:
  - name: checkout latest
    git:
      repo: https://github.com/emory-libraries/dlp-selfdeposit
      dest: files/checkout
      version: main
  - name: get ec2host ip
    ec2_instance_info:
      filters:
        "tag:Name": OE24-hyrax-{{ ENV }}
    register: instance_ip
  - name: get fedora ip
    ec2_instance_info:
      filters:
        "tag:Name": OE24-fedora-{{ ENV }}
    register: fedora_instance
  - name: set FEDORA_HOST fact
    set_fact:
      FEDORAHOST: "{{ fedora_instance.instances[0].network_interfaces[0].private_ip_address }}"
  - name: get DBHOST
    rds_instance_info:
      db_instance_identifier: "fedora-depo-{{ ENV }}"
    register: DBHOST_info
  - name: set DBHOST
    set_fact: 
      DBHOST: "{{ DBHOST_info.instances[0].endpoint.address }}"
  - name: get REDIS Info
    elasticache_info:
      name: "oe24-redis-{{ ENV }}"
    register: redis_info
  - name: set redis fact
    set_fact:
      REDISHOST: "{{ redis_info.elasticache_clusters[0].cache_nodes[0].endpoint.address }}"
  - name: populate template
    template:
      src: files/env.production.j2
      dest: files/checkout/.env.production 
  - name: deploy
    shell:
      cmd: "BRANCH=main bundle exec cap test deploy"
      chdir: files/checkout
    args:
      executable: /bin/bash
    environment: 
      "{{ deploy_host }}": "{{ instance_ip.instances[0].network_interfaces[0].private_ip_address }}"
