- import_playbook: oe-stack.yaml
- import_playbook: install_tomcat_and_fedora.yaml
- import_playbook: install_hyrax_dependencies.yaml
- import_playbook: solr_core.yaml 
- import_playbook: deploy.yaml
- import_playbook: admin_sets.yaml
