# frozen_string_literal: true
require './lib/preservation_event_model_methods'

# Generated by hyrax:models:install
class FileSet < Hyrax::FileSet
  PRIMARY = 'Primary Content'
  SUPPLEMENTAL = 'Supplemental Content'
  PRESERVATION = 'Supplemental Preservation'

  include Hyrax::Schema(:emory_file_set_metadata)
  include PreservationEventModelMethods

  def extracted_text_content
    extracted_text&.file&.read
  end
end
